annotations:
  artifacthub.io/changes: |
    - "[Added]: Dashboard manifests"
apiVersion: v2
appVersion: v1.0.2
description: A Helm chart for Argo Rollouts
home: https://github.com/argoproj/argo-helm
icon: https://argoproj.github.io/argo-rollouts/assets/logo.png
maintainers:
- name: alexmt
- name: dthomson25
- name: jessesuen
name: argo-rollouts
version: 2.0.0
